### ISSUE TITLE
Random Number Guess in Python 

### ISSUE THREAD

**Issue by adarshherohoo** [samhackathon/Hacktoberfest-2021-Open-First-Pull-Request#6365]
Want to add a program for random number gusesssing game in Python.
@ossamamehmood  can you please assign it to me .Thank you

**Comment by rishuraj1708** [comment]
Hii sir is this open .

**Comment by joshiadarshx** [comment]
> Hii sir is this open .

i am waiting for them to assign bro

**Comment by akash47angadi** [comment]
assign me
@ossamamehmood

**Comment by joshiadarshx** [comment]
@ossamamehmood assign it to me
